apiVersion: 1
datasources:
  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100
    access: proxy

  - name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo:3200
    access: proxy

  - name: Mimir
    uid: mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "anonymous"
